//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbYusandyShoppingCarEntities : DbContext
    {
        public dbYusandyShoppingCarEntities()
            : base("name=dbYusandyShoppingCarEntities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
       // {
         //   throw new UnintentionalCodeFirstException();
       // }
    
        public virtual DbSet<BakeFood> BakeFood { get; set; }
        public virtual DbSet<ChineseFood> ChineseFood { get; set; }
        public virtual DbSet<ColubiaFood> ColubiaFood { get; set; }
        public virtual DbSet<Drink> Drink { get; set; }
        public virtual DbSet<FranceFood> FranceFood { get; set; }
        public virtual DbSet<JapaneseFood> JapaneseFood { get; set; }
        public virtual DbSet<MemberData> MemberData { get; set; }
        public virtual DbSet<OldFood> OldFood { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Orderdetail> Orderdetail { get; set; }
        public virtual DbSet<SkinFood> SkinFood { get; set; }
        public virtual DbSet<ThiFood> ThiFood { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
