//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drink
    {
        public int Id { get; set; }
        public string PId { get; set; }
        public string Name { get; set; }
        public string FoodPacket { get; set; }
        public Nullable<int> Price1 { get; set; }
        public string Img { get; set; }
    }
}
