//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberData
    {
        public int Id { get; set; }
        public string mAccount { get; set; }
        public string mPasswd { get; set; }
        public string mFName { get; set; }
        public string mSex { get; set; }
        public string mPhone { get; set; }
        public Nullable<System.DateTime> mBirthday { get; set; }
        public string mEmail { get; set; }
        public string mAddress { get; set; }
    }
}
